-- CMS文章评论表
CREATE TABLE IF NOT EXISTS `promotion_cms_article_comment` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID',
    `article_id` BIGINT NOT NULL COMMENT '文章ID',
    `user_id` BIGINT NOT NULL COMMENT '评论者用户ID',
    `user_nickname` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '评论者昵称',
    `user_avatar` VARCHAR(255) DEFAULT NULL COMMENT '评论者头像',
    `anonymous` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否匿名',
    `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父评论ID,0表示一级评论',
    `content` TEXT NOT NULL COMMENT '评论内容',
    `pic_urls` VARCHAR(2000) DEFAULT NULL COMMENT '评论图片数组,JSON格式',
    `visible` BIT(1) NOT NULL DEFAULT b'1' COMMENT '是否可见',
    `reply_count` INT NOT NULL DEFAULT 0 COMMENT '回复数量',
    `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数量',
    `read_status` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否已读',
    `article_author_id` BIGINT NOT NULL COMMENT '文章作者ID,冗余字段',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    PRIMARY KEY (`id`),
    INDEX `idx_article_id` (`article_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_parent_id` (`parent_id`),
    INDEX `idx_article_author_id` (`article_author_id`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CMS文章评论表';
