# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NameServer配置文件

# NameServer监听端口，默认9876
listenPort=9876

# 服务器回调线程池线程数量
serverCallbackExecutorThreads=0

# 服务器工作线程池线程数量
serverWorkerThreads=8

# 服务器公共线程池线程数量
serverPublicExecutorThreads=0

# 服务器扫描HA线程池线程数量，默认为1
serverChannelMaxIdleTimeSeconds=120

# 网络连接最大空闲时间，默认120s
serverSocketRcvBufSize=65535

# 网络socket接收缓冲区大小，默认65535
serverSocketSndBufSize=65535

# 服务端限流阈值，默认256
serverOnewaySemaphoreValue=256

# 服务端异步调用信号量值，默认64
serverAsyncSemaphoreValue=64

# 扫描不活跃的broker的时间间隔，单位毫秒，默认5秒
scanNotActiveBrokerInterval=5000

# KV配置管理器
kvConfigPath=${user.home}/namesrv/kvConfig.json

# 配置文件路径
configStorePath=${user.home}/namesrv/namesrv.properties

# 产品环境建议关闭
productEnvName=center

# 集群测试
clusterTest=false

# 顺序消息功能
orderMessageEnable=false
