# 构建阶段
FROM node:20 AS builder

# 设置工作目录
WORKDIR /app

# 配置Node环境变量，增加内存限制
ENV NODE_OPTIONS="--max-old-space-size=8192"

# 配置npm使用国内镜像源
RUN npm config set registry https://registry.npmmirror.com

# 接收前端项目路径参数
ARG FRONTEND_PROJECT_PATH
ARG NODE_ENV

# 首先复制package.json和package-lock.json用于缓存依赖
COPY ${FRONTEND_PROJECT_PATH}/package*.json /app/

# 安装依赖
RUN npm install

# 然后复制其余项目文件
COPY ${FRONTEND_PROJECT_PATH}/ /app/

# 构建项目
RUN npm run build:prod

# 运行阶段
FROM nginx:alpine

# 复制构建产物
COPY --from=builder /app/dist /usr/share/nginx/html

# 复制 nginx 配置
COPY devops/docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf

# 暴露端口
EXPOSE 80

# 添加健康检查
HEALTHCHECK --interval=30s --timeout=3s CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]
