# 第一阶段：构建
FROM openjdk:17-jdk-slim AS builder
WORKDIR /app
COPY backend/hissp-distribution/distribution-server/target/distribution-server.jar /app/app.jar

# 第二阶段：运行
FROM openjdk:17-jdk-slim
WORKDIR /app

# 复制jar包
COPY --from=builder /app/app.jar /app/app.jar

# 替换为国内镜像源并更新
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update

# 安装区域设置、基础工具和字体配置工具
RUN apt-get install -y --no-install-recommends tzdata curl fontconfig locales

# 设置中文语言环境
RUN sed -i 's/# zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen zh_CN.UTF-8

# 设置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 生成字体缓存
RUN fc-cache -fv

# 清理
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 设置环境变量
ENV TZ=Asia/Shanghai
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

# 暴露端口
EXPOSE 48080

# 启动命令
ENTRYPOINT exec java ${JAVA_OPTS} -jar app.jar ${ARGS}
